[project]
    authors=[{name="Sckathach", email="thomas.winninger68@gmail.com"}]
    dependencies=[
        "jupyter (>=1.1.1,<2.0.0)",
        "qiskit-aer (>=0.17.0,<0.18.0)",
        "qiskit[all] (>=2.0.0,<3.0.0)",
        "rich (>=14.0.0,<15.0.0)",
    ]
    description=""
    name="causapscal-des-profondeurs"
    readme="README.md"
    requires-python=">=3.13,<4.0"
    version="0.1.0"

[build-system]
    build-backend="poetry.core.masonry.api"
    requires=["poetry-core>=2.0.0,<3.0.0"]

[tool.poetry]
    package-mode=false

[tool.poetry.group.api.dependencies]
toml = "^0.10.2"
fastapi = "^0.115.12"
uvicorn = "^0.34.2"


[tool.poetry.group.dev.dependencies]
mypy = "^1.15.0"
ruff = "^0.11.8"

[[tool.mypy.overrides]]
    ignore_missing_imports=true
    module=["qiskit.*", "qiskit_aer.*"]

[tool.pyright]
    ignore=["qiskit", "qiskit_aer"]
